# Generated by Django 4.2.9 on 2024-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="hair_color",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="weight",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
