# Generated by Django 4.2.9 on 2024-01-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_person_daybirth_person_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
