# Generated by Django 4.2.9 on 2024-01-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_person_age_alter_person_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
